// Builds a plain-text encounter summary for copy/paste into a chart note.
// Kept as a pure function (formData/results/recommendations in, string out)
// so it's easy to keep in sync with whatever sections generateRecommendations()
// produces.

function fmtPct(fraction) {
  return `${(fraction * 100).toFixed(1)}%`;
}

const SECTION_ORDER = [
  ["lipid", "Lipid management"],
  ["bp", "Blood pressure"],
  ["aspirin", "Aspirin"],
  ["diabetes", "Diabetes"],
  ["ckd", "CKD staging"],
  ["heartFailure", "Heart failure"],
  ["cha2ds2vasc", "CHA2DS2-VASc"],
  ["ckm", "CKM staging"]
];

export function buildSummaryText({ formData, results, recommendations }) {
  const lines = [];
  const now = new Date();

  lines.push("PREVENT RISK SUMMARY");
  lines.push(now.toLocaleDateString() + " " + now.toLocaleTimeString());
  lines.push("");
  lines.push(
    `Age ${formData.age || "—"} | Sex ${formData.sex || "—"} | SBP/DBP ${formData.sbp || "—"}/${formData.dbp || "—"} | ` +
      `TC ${formData.totalChol || "—"} HDL ${formData.hdl || "—"} LDL ${formData.ldl || "—"} | BMI ${formData.bmi || "—"} | eGFR ${formData.egfr || "—"}`
  );

  const historyFlags = [
    formData.smoker && "current smoker",
    formData.diabetes && "diabetes",
    formData.bpMeds && "on BP meds",
    formData.statin && "on statin",
    formData.priorMI && "prior MI",
    formData.priorStroke && "prior stroke/TIA",
    formData.priorPAD && "prior PAD",
    formData.acsWithin12mo && "ACS <12mo",
    formData.priorRevasc && "prior revascularization",
    formData.heartFailureHistory && "heart failure history",
    formData.atrialFibrillation && "AFib",
    formData.familyHistory && "family history of premature ASCVD"
  ].filter(Boolean);
  if (historyFlags.length) lines.push("History: " + historyFlags.join(", "));

  if (results) {
    lines.push("");
    lines.push("PREVENT RISK (10-yr / 30-yr)");
    lines.push(`  Total CVD: ${fmtPct(results.risks.cvd[10])} / ${fmtPct(results.risks.cvd[30])}`);
    lines.push(`  ASCVD:     ${fmtPct(results.risks.ascvd[10])} / ${fmtPct(results.risks.ascvd[30])}`);
    lines.push(`  Heart failure: ${fmtPct(results.risks.hf[10])} / ${fmtPct(results.risks.hf[30])}`);
  }

  if (recommendations) {
    lines.push("");
    lines.push("RECOMMENDATIONS");
    for (const [key, label] of SECTION_ORDER) {
      const section = recommendations[key];
      if (!section) continue;
      lines.push("");
      lines.push(`[${label}]${section.riskGroup ? " — " + section.riskGroup : ""}`);
      for (const bullet of section.bullets) lines.push(`  - ${bullet}`);
    }
  }

  lines.push("");
  lines.push("Generated by PREVENT Risk Suite (local, no data transmitted). Decision support only — not a substitute for clinical judgment.");

  return lines.join("\n");
}
